GET {{url}}/cuisines/

###

GET {{url}}/cuisines/cuisine/1

###

POST {{url}}/cuisines/cuisine
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{
  "name": "Danish",
  "description": "salty and savory",
  "flavor_profile": "salty"
}

###


PUT {{url}}/cuisines/cuisine/3
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{
  "name": "Indian2",
  "description": "updated description",
  "flavor_profile": "Complex, warm, spicy, and aromatic"
}

###

DELETE {{url}}/cuisines/cuisine/1
Authorization: Bearer {{jwt_token}}


###