GET {{url}}/users/
###


GET{{url}}/
###
GET {{url}}/users/jj/favorites
Authorization: Bearer {{jwt_token}}


###
POST {{url}}/
###
POST {{url}}/users/bb/favorites/spices/9
Authorization: Bearer {{jwt_token}}

###
POST {{url}}/users/jj/favorites
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{

  "name": "oo"
}

###
POST {{url}}/users/jj/favorites/cuisines/2
Authorization: Bearer {{jwt_token}}

